# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:06
from __future__ import unicode_literals

import core_flavor.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to=core_flavor.models.UUIDUploadTo('arcgis/thumbnails/%Y/%m/')),
            preserve_default=False,
        ),
    ]
