# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:38
from __future__ import unicode_literals

import core_flavor.models
import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arcgis_marketplace', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid youtube url', regex='^(https?\\:\\/\\/)?(www\\.youtube\\.com|youtu\\.?be)\\/.+$')]),
        ),
        migrations.AddField(
            model_name='webmapingapp',
            name='configuration',
            field=models.TextField(default='', verbose_name='configuration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=core_flavor.models.UUIDUploadTo('arcgis/thumbnails/%Y/%m/'), verbose_name='image'),
        ),
    ]
